/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={inter.className}>
        <div className='container mx-auto max-w-[1200px] flex items-center gap-8 px-4 py-4'>
          <Image
            src='/images/logo.png' // Route of the image file
            height={80} // Desired size with correct aspect ratio
            width={80} // Desired size with correct aspect ratio
            alt='Your Name'
          />

          <h1 className='text-xl font-bold'>
            INDIAN SOCIETY FOR TECHNICAL EDUCATION
          </h1>
        </div>

        <div className='border border-primary'>
          <div className='navbar uppercase p-0 min-h-fit px-4 mx-auto max-w-[1200px]'>
            <Link href='/' className={styles.linkActive}>
              Home
            </Link>
            <Link href='/about' className={styles.link}>
              About
            </Link>
          </div>
        </div>

        <div className='carousel w-full'>
          <div id='slide1' className='carousel-item relative w-full'>
            <img
              src='http://www.isteonline.in/DataFiles/Content/228_flag%20hoisting.jpg'
              alt=''
              className='w-full'
            />
            <div className='absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2'>
              <a href='#slide4' className='btn btn-circle'>
                ❮
              </a>
              <a href='#slide2' className='btn btn-circle'>
                ❯
              </a>
            </div>
          </div>
          <div id='slide2' className='carousel-item relative w-full'>
            <img
              src='https://placeimg.com/800/200/arch'
              alt=''
              className='w-full'
            />
            <div className='absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2'>
              <a href='#slide1' className='btn btn-circle'>
                ❮
              </a>
              <a href='#slide3' className='btn btn-circle'>
                ❯
              </a>
            </div>
          </div>
          <div id='slide3' className='carousel-item relative w-full'>
            <img
              src='https://placeimg.com/800/200/arch'
              alt=''
              className='w-full'
            />
            <div className='absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2'>
              <a href='#slide2' className='btn btn-circle'>
                ❮
              </a>
              <a href='#slide4' className='btn btn-circle'>
                ❯
              </a>
            </div>
          </div>
          <div id='slide4' className='carousel-item relative w-full'>
            <img src='https://placeimg.com/800/200/arch' className='w-full' />
            <div className='absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2'>
              <a href='#slide3' className='btn btn-circle'>
                ❮
              </a>
              <a href='#slide1' className='btn btn-circle'>
                ❯
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
